version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - .data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-api
    command: npm run debug
    volumes:
      - ./dist:/usr/ws/clean-api/dist
      - ./package.json:/usr/ws/clean-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
